name: Check for broken links on site

on:
  push:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "**.html"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "!.github/workflows/prettier.yml"
      - "!.github/workflows/lighthouse-badger.yml"
      - "!lighthouse_results/**"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "**.html"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "!.github/workflows/prettier.yml"
      - "!.github/workflows/lighthouse-badger.yml"
      - "!lighthouse_results/**"

permissions:
  contents: read

jobs:
  check-links-on-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.299.0
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
      - name: Update _config.yml
        run: |
          sed -i "s|^  repo:.*|  repo: ${{ github.repository }}|" _config.yml
          sed -i "s|^baseurl:.*|baseurl: |" _config.yml
      - name: Install ImageMagick
        run: sudo apt-get install -y imagemagick
      - name: Install and Build
        run: |
          export JEKYLL_ENV=production
          bundle exec jekyll build
      - name: Purge unused CSS
        run: |
          npm install -g purgecss
          purgecss -c purgecss.config.js
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.8.0
        with:
          fail: true
          # only check local links; --root requires base path for resolving root-relative URLs
          args: --offline --root-dir _site --remap '_site(/?.*)/assets/(.*) _site/assets/$2' --verbose --no-progress '_site/**/*.html'
